language: node_js
node_js:
  - node

script:
  - npm test
  - npm run build

cache:
  directories:
  - node_modules

deploy:
  provider: surge
  project: ./build/
  domain: svg-manipulator.codingbad.me
  skip_cleanup: true
